EMACS_INFO="/Applications/Emacs.app/Contents/Resources/info"
EMACS_BIN="/Applications/Emacs.app/Contents/MacOS/bin"
export INFOPATH=$EMACS_INFO:/usr/local/info:/usr/local/share/info:$INFOPATH
export PYTHONPATH=~/util/lib/python2.6/site-packages
export SVN_EDITOR=emacsclient
export EDITOR='mg -f auto-fill-mode'
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
#export JAVA_HOME=/opt/seth/resources/java/soylatte16-i386-1.0.3
# don't let tar, etc copy Finder specific junk.
export COPY_EXTENDED_ATTRIBUTES_DISABLE=true

typeset -U path
path=(
    ~/util/bin
    /usr/local/bin
    ~/util/python/bin
    /Library/Frameworks/Python.framework/Versions/Current/bin
    ~/scm/bin
    /opt/local/bin
    /opt/local/sbin
    /usr/local/texlive/2007/bin/i386-darwin
    /usr/texbin
    ${JAVA_HOME}/bin
    $EMACS_BIN
    $path
)
     
for f in ${HOME}/.zsh/lib/*; source $f

cdpath=( . ~/src ~/Notebook ~/Dropbox ~/Documents )

chpwd() {
    [[ -t 1 ]] || return
    case $TERM in
      sun-cmd) print -Pn "\e]l%~\e\\"
        ;;
      *xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;%3~\a"
        ;;
    esac
}
chpwd

bindkey -e

zmodload -i zsh/complist
bindkey -M menuselect '^o' accept-and-infer-next-history
bindkey '^?' backward-delete-char
#
#---


#--- zsh options ---
#
setopt autopushd cdablevars autocd extendedglob histignorealldups 
setopt appendhistory extendedhistory histsavenodups pushdignoredups
setopt histfindnodups combiningchars
unsetopt beep nomatch

#--- Shell Functions ---
#
fpath+=(
  ${HOME}/.zsh/functions
)
export GEMDIR=$(gem environment | grep -A1 'GEM PATHS' | tail -1 | awk '{print $2}')
autoload splitpath wcat wcd wfile wg wll gemdoc

#--- load the completion stuff
. ${HOME}/.zshcomp
for f in ${HOME}/.zsh/bash_completion.d/*; source $f

#--- Fix for emacs key binding
WORDCHARS=${WORDCHARS//[\/]}

#--- Git prompt setup
autoload -Uz vcs_info

autoload colors
colors

precmd() {
  psvar=()
  vcs_info
  [[ -n $vcs_info_msg_0_ ]] && psvar[1]="$vcs_info_msg_0_"
}

PROMPT='[%m] %2~: '
RPROMPT="%(1v.%{$fg[yellow]%}%1v%f.)%{$reset_color%}"
